source "https://rubygems.org"

gem "sass",           "~> 3.3"
gem "compass",        ">= 1.0.0.alpha.20",  "< 2"

gem "breakpoint",     "~> 2.4"
gem "sass-globbing",  "~> 1.1"
gem "susy",           "~> 2.1"

ruby "2.0.0"
